name: Veracode Build Ruby Code Package

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest           #${{ vars.CLIENT_ENV || 'ubuntu-latest' }}
    container:
      image: ruby:latest     #${{ vars.CLIENT_IMAGE_URL || 'veracode/scm-packaging' }}:${{ vars.CLIENT_IMAGE_TAG || '2.1.0' }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          token: ${{ inputs.token }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: s3.3.4

      - name: Cache bundle dependencies
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundle-

      - name: Install Dependencies
        run: bundle install --path vendor/bundle

      - name: Package the Gem
        run: |
          gem build "*.gemspec"

      - uses: actions/checkout@v4
        with:
          path: 'veracode-helper'

      - name: Package the application
        id: application_package
        run: |  
          cd veracode-helper/helper/cli
          cliFile=$(ls -1 . | head -n 1)
          cliFileName=$(echo "$cliFile" | cut -c 1-$((${#cliFile}-7)))
          tar -zxvf $cliFile
          cd $cliFileName
          export PATH="veracode-helper/helper/cli/$cliFileName:$PATH"
          cd /__w/veracode/veracode
          veracode package --source . --output veracode-artifacts --trust

#      - name: Package the application
#        id: application_package
#        env:
#          VERACODE_API_KEY_ID: '${{ secrets.VERACODE_API_ID }}'
#          VERACODE_API_KEY_SECRET: '${{ secrets.VERACODE_API_KEY }}'
#        run: |
#          cd veracode-helper/helper/cli
#          cliFile=$(ls -1 . | head -n 1)
#          cliFileName=$(echo "$cliFile" | cut -c 1-$((${#cliFile}-7)))
#          tar -zxvf $cliFile
#          cd $cliFileName
#          export PATH="veracode-helper/helper/cli/$cliFileName:$PATH"
#          cd /__w/veracode/veracode
#          veracode package --source . --output veracode-artifacts --trust

#      - uses: actions/checkout@v4
#        with:
#          path: 'veracode-helper'

      - uses: actions/upload-artifact@v4
        with:
          name: veracode-artifact
          path: "devise-5.0.0.beta.gem"